### ISSUE TITLE
Can't Load roms

### ISSUE THREAD

**Issue by rainthefrog** [risolvipro/PlayGB#11]
Playdate OS: 2.4.2
PlayGB: 0.7.5

I can see the list of roms (all .gb), but whenever I try to load them it says "Oh no! Can't load the selected ROM"

**Comment by risolvipro** [comment]
Hi, did you try loading popular roms? E.g. Super Mario Land

**Comment by rainthefrog** [comment]
Yes

**Comment by risolvipro** [comment]
Are you sure the file format is correct? The emulator doesn't support zip files, so if you rename a .zip to .gb, it won't work.
Also, please try with other emulators for Playdate and let me know.

**Comment by rainthefrog** [comment]
Yes - .gb and gamekid loads the roms fine

**Comment by risolvipro** [comment]
Thanks, I just tried on Playdate OS 2.4.2 but it's working for me (I have a Rev A device).

Not sure what the issue is. Did you sideload it from the Playdate website?

**Comment by rainthefrog** [comment]
Hmm, yes I did. I'm trying pokemon blue and Link's awakening. When I get the chance I will try super Mario land. I'm pretty new to this - is there debug steps somewhere?

**Comment by rainthefrog** [comment]
Also tried Super Mario Land - same thing. I'm pretty sure I have rev B? I picked this up last week.

Also tried 0.6 and 0.7 and same result. However, 0.7 and 0.7.5 crash the whole OS when failing to load the rom. 0.6 I can go back to library

**Comment by fejx** [comment]
Hi, I have a similiar if not identical issue:

I have tried the following roms so far:
* Pokemon Yellow German (MD5 `E93F10168E3C9B9D18E3AD4A1415E1D0`)
* Zelda Link's Awakening German (MD5 `8B7AF1A8CA96C74301D633E0CE83BA0B`)
* Super Mario Land (MD5 `B48161623F12F86FEC88320166A21FCE`)
* Tetris (MD5 `084F1E457749CDEC86183189BD88CE69`)

Each of these roms work fine on other emulators like:
* MyOldBoy! (Android)
* PizzaBoy (Android)
* Gamekid (Playdate)
* Probably others, I have been using these for a while.

## Reproduction

For each of this roms, selecting them in PlayGB's library scene leads to this text:
> Oh no!
> Can't load the selected ROM

Navigating back to Library or Home results in the Playdate crashing. I doubt that this will be helpful, but just in case, here is the crashlog:
```
--- crash at 2024/03/28 22:46:26---
build:5cd9814a-2.4.2-release.166897-buildbot
   r0:00000007    r1:2403f627     r2:3000027c    r3: 00000000
  r12:00001ff0    lr:2403f627     pc:2405d4be   psr: 810f0000
 cfsr:00000082  hfsr:00000000  mmfar:00000007  bfar: 00000007
rcccsr:00000000
heap allocated: 180896
Lua totalbytes=0 GCdebt=0 GCestimate=0 stacksize=0
```

I am running the newest versions OS 2.4.2 and PlayGB 0.7.5. I am not sure about my hardware rev, but ordered just 3 weeks ago so it's probably the latest.

---

As soon as I get a chance, I will try and get the code compiling on my machine and try out a debug build. Since Gamekid is based on Peanut_GB as well, the cause for this issue is probably not the actual emulation code. I *should* be able to isolate the cause for this if I tinker with it a bit.

**Comment by risolvipro** [comment]
Thanks for the info, here's a build compiled with the latest SDK (I also changed/fixed some things)

[PlayGB-test.pdx.zip](https://github.com/risolvipro/PlayGB/files/14796653/PlayGB-test.pdx.zip)

If you can, install the Simulator and connect the Playdate, it should give you a message such as "Can't open rom file" or "Can't read rom file" in the console.

**Comment by fejx** [comment]
Yes indeed, here is the full output:

```
01:25:01: Device Connected: /dev/ttyACM0
stats
echo off
target=h7d1
build=5cd9814a-2.4.2-release.166897-buildbot-240319
boot_build=5cd9814a-2.4.2-release.166897-buildbot
SDK=2.4.2
pdxversion=20400
serial#=PDU1-YXXXXXX
cc=9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
crashed=1
pcbver=0x13
time and date set
src/game_scene.c:197: Can't open rom file games/Tetris (World).gb
```
Is that helpful?

**Comment by risolvipro** [comment]
Thanks for the help!

New build: [PlayGB-test2.pdx.zip](https://github.com/risolvipro/PlayGB/files/14797294/PlayGB-test2.pdx.zip)

It should give you a file error message.

**Comment by fejx** [comment]
Yes:
```
src/game_scene.c:198: Can't open rom file games/Tetris (World).gb
src/game_scene.c:199: File error unknown uC-FS error: 0709
```

**Comment by risolvipro** [comment]
Thanks!

If you haven't already done so, can you copy the pdx over USB to the /Games folder? The Data folder for the game will be different (com.risolvipro.playgb).

**Comment by fejx** [comment]
Up until now, I deployed the PDX files via the web sideloader, but I just tried it out like you suggested. Just to be sure, this is where it is at now:
```
$ pwd
/media/fejx/PLAYDATE/Games/PlayGB.pdx
$ ls
fonts  games  images  launcher  pdex.bin  pdex.dylib  pdxinfo
```
The console output still is:
```
src/game_scene.c:198: Can't open rom file games/Tetris (World).gb
src/game_scene.c:199: File error unknown uC-FS error: 0709
```

**Comment by risolvipro** [comment]
Okay, I think I found the issue.

I see a "games" folder in your pdx (it shouldn't be there), the correct folder is /Data/com.risolvipro.playgb (USB) or /Data/user.*.com.risolvipro.playgb (web sideload)

**Comment by fejx** [comment]
Well, this is embarrassing. This fixed the issue indeed. I probably should have read the manual more closely. Thank you for your patience and custom builds and sorry for the inconveniences caused by my inability to follow instructions 🥲

**Comment by risolvipro** [comment]
No problem, it's a very odd issue because the `playdate->file->listfiles` function considers the pdx folder and Data folder as a single folder.

**Comment by rainthefrog** [comment]
@fejx you and I both. This was also my issue. Working after moving to Data!

**Comment by rainthefrog** [comment]
Maybe a dummy proof solution would be checking the pdx location as a fallback?

**Comment by fejx** [comment]
~I'll try out if I can make it work regardless of the path.~ *Wait, that's what you are saying, right?* If that's not possible, I would rather suggest to add a hint to the error message that this might be the cause for the error.

**Comment by risolvipro** [comment]
> Maybe a dummy proof solution would be checking the pdx location as a fallback?

I think I can't check the full location of the file (paths are relative). Maybe I could catch the error code `0709`

**Comment by risolvipro** [comment]
@fejx @rainthefrog Added an error message in the latest version (based on the error code)
