### ISSUE TITLE
Cannot save game

### ISSUE THREAD

**Issue by panpil** [risolvipro/PlayGB#12]
Hello Team

First of all thanks a lot for your excellent software! I have an issue.
I believe that the Save game function is not working. When I click on "Save" and then when I go to /Data/*.playgb/saves/ the folder is empty. Is this normal behaviour please? 

Furthermore, what is the method, please, for restoring a save game? 
I am using PlayGB 0.7.6 and Playdate OS 2.4.2

thank you for your help :-)

**Comment by fejx** [comment]
The save menu option is a little bit misleading.

You need to use the ingame save function to save. PlayGB does not support saving states, so using save in the menu does not actually save the current state (i.e. the game ram). Instead, the menu option makes sure the sav-file that was saved ingame is actually written to disc. If you do not use the menu option, the sav-file is kept in memory until you stop the game.

**Comment by panpil** [comment]
> The save menu option is a little bit misleading.
> 
> You need to use the ingame save function to save. PlayGB does not support saving states, so using save in the menu does not actually save the current state (i.e. the game ram). Instead, the menu option makes sure the sav-file that was saved ingame is actually written to disc. If you do not use the menu option, the sav-file is kept in memory until you stop the game.

It is very clear, thank you for the quick response!
