### ISSUE TITLE
browse gamelist with crank

### ISSUE THREAD

**Issue by slydog43** [risolvipro/PlayGB#2]
Love your build, but wouldn't it be cool to be able to scroll gamelist with the crank.  Thanks

**Comment by risolvipro** [comment]
Sorry for the delay, it's a good idea, maybe in the next releases.

**Comment by technoturk** [comment]
I also need a fast page scroll, when i have over 1000 roms it takes long time to scroll all the way down. Maybe add Left/Right buttons for pagescroll to Up/Down.

**Comment by risolvipro** [comment]
Thanks for the feedback, I'm working on a fast scrolling option with d-pad.

**Comment by risolvipro** [comment]
Added fast scrolling and crank scrolling in 0.7.5 1819e361eead9e02cb25a6ee6295adfd412d8a37
