### ISSUE TITLE
1:1 Pixel Scaling

### ISSUE THREAD

**Issue by PascalPixel** [risolvipro/PlayGB#4]
Hi @risolvipro thanks for making this!

I know it'd only be displaying at 60% of the screen height, but could you add a 1:1 pixel mode for the 160x144 resolution of the gameboy? The screen is very sharp and I think it would look gorgeous.

**Comment by risolvipro** [comment]
Hi!

PlayGB uses a 2x scaling to get pixel perfect graphics and it's quite fast. I think I tried the 1:1 scaling but it was slower.

**Comment by PascalPixel** [comment]
It's also unusable for anything but typography since the Playdate is monotone, not grayscale 😂 
The upscaling creates the shades for the Gameboy! Thanks for making it @risolvipro

**Comment by PascalPixel** [comment]
@risolvipro great job on optimization since i last tried!
