### ISSUE TITLE
Unable to copy games to Playdate

### ISSUE THREAD

**Issue by stuffbyjk** [risolvipro/PlayGB#6]
Hello!

I'm excited to try PlayGB on my new Playdate, but ran into a snag when trying to add ROM files.

I followed the instructions for mounting the playdate in Disk Mode, but have these two issues:

1. The folder structure is different on my console: D:\Data\user.32100.com.risolvipro.playgb\games
2. I get a permissions error when trying to write anything to the folder. I went into properties for the games folder, as well as the parent folder(s) and they keep defaulting to Read Only

Any idea how I can overcome this? Is there something I need to do at the console level to enable write access to the Playdate?

Thanks!
-Jake
![Write_Error](https://github.com/risolvipro/PlayGB/assets/139893198/fc32e6e5-3709-4d8f-90a8-6eb15314eb98)

**Comment by risolvipro** [comment]
Folder structure is different for games sideloaded through the website, did you try installing PlayGB in Disk Mode? Just copy the pdx in /Games folder, start PlayGB again then copy the files in `/Data/com.risolvipro.playgb/games/`

**Comment by stuffbyjk** [comment]
Thank you for the reply!

Makes sense that sideloading online is a bit different. That is indeed how I installed the first time.

I just tried to drag-n-drop your PDX file into the Games folder while in Disk Mode, and ran into the same permissions error. That folder remains to be Read Only. ☹️

**Comment by risolvipro** [comment]
Oh, that's odd.

I think I can't help you but I suggest you to:

- Try with a different USB port or PC
- Reach out Panic support
