### ISSUE TITLE
Trouble with saving

### ISSUE THREAD

**Issue by CaelumSaltare** [risolvipro/PlayGB#9]
I was playing pokemon blue on another PD emulator called Gamekid, and wanted to transfer the save file from that run to PlayGB. 
The usual method of copying and loading the save file into the saves folder in data yeilded no results and my hope is that you might be able extend the emulator to have this capability (Your performance is overall slightly better than GameKid's).

**Comment by risolvipro** [comment]
Hi, I didn't tried, but the save file should be compatible.
Please check the name of the save file, it should match the game name but with .sav extension.

**Comment by CaelumSaltare** [comment]
The file that I wish to transfer bears the same name as its original ( I am simply copying it over from its original location).
What seems to be happening everytime I place it in the play Gb data folder is that a new save file  is created. 
I've tried creating a save in the rom by entering the game and then saving manually, then replacing it with my file, but still no luck. 

Edit: Is it something to do with the save option on the system pause button's menu?

**Comment by risolvipro** [comment]
I noticed that Gamekid alters the name of the save (game.gb becomes gam.sav). So rename the save file matching the game name (games/game.gb, saves/game.sav).

**Comment by CaelumSaltare** [comment]
OMG, it was off by a single "]", had to really dig deep there. Thanks for the help :)
